#property copyright "Generated by GPT-5 Codex"
#property link      "https://github.com/"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Calendar\Calendar.mqh>

enum OscillatorMode
  {
   OSC_RSI = 0,
   OSC_CCI = 1
  };

input string          InpStrategyTag                = "Gold_DCA_UTBot";
input ulong           InpMagicNumber                = 5102025;
input double          InpInitialLot                 = 0.10;
input double          InpLotMultiplier              = 1.50;
input double          InpStepPoints                 = 500.0;
input uint            InpMaxPositionsPerSide        = 6;
input bool            InpUseOnlyNewBarSignals       = true;
input int             InpSlippage                   = 30;

input ENUM_TIMEFRAMES InpSignalTF                   = PERIOD_M15;
input int             InpFastEMA                    = 34;
input int             InpSlowEMA                    = 89;

input bool            InpUseTrendFilter             = true;
input ENUM_TIMEFRAMES InpTrendTF                    = PERIOD_H1;
input int             InpTrendFastEMA               = 55;
input int             InpTrendSlowEMA               = 144;

input bool            InpUseOscillatorFilter        = true;
input OscillatorMode  InpOscillatorMode             = OSC_RSI;
input int             InpRSIPeriod                  = 14;
input int             InpCCIPeriod                  = 20;
input double          InpOscillatorBuyLevel         = 55.0;
input double          InpOscillatorSellLevel        = 45.0;

input int             InpUTAtrPeriod                = 10;
input double          InpUTAtrMultiplier            = 1.5;

input double          InpBasketTakeProfitUSD        = 8.0;
input double          InpBasketTrailingStartUSD     = 5.0;
input double          InpBasketTrailingLockUSD      = 3.0;
input double          InpBasketQuickCloseUSD        = 1.0;

input bool            InpEnableHedging              = true;
input double          InpHedgeMarginLevel           = 140.0;
input uint            InpHedgeCooldownMinutes       = 15;

input bool                    InpUseNewsFilter      = true;
input ENUM_CALENDAR_IMPORTANCE InpNewsMinImpact     = CALENDAR_IMPORTANCE_HIGH;
input uint                    InpNewsMinutesBefore  = 30;
input uint                    InpNewsMinutesAfter   = 30;
input bool                    InpNewsBlockBuys      = true;
input bool                    InpNewsBlockSells     = true;
input bool                    InpAllowDcaDuringNews = false;
input bool                    InpAllowHedgeDuringNews = true;

//--- constants & globals
const int             DIR_BUY                       = 1;
const int             DIR_SELL                      = -1;

CTrade                trade;

datetime              g_lastSignalBarTime           = 0;
int                   g_pendingDirection            = 0;

double                g_utFinalUpper                = 0.0;
double                g_utFinalLower                = 0.0;
int                   g_utTrend                     = 0;
bool                  g_utInitialized               = false;

datetime              g_lastHedgeTimeBuy            = 0;
datetime              g_lastHedgeTimeSell           = 0;

int                   g_handleATR                   = INVALID_HANDLE;
int                   g_handleEMAfast               = INVALID_HANDLE;
int                   g_handleEMAslow               = INVALID_HANDLE;
int                   g_handleRSI                   = INVALID_HANDLE;
int                   g_handleCCI                   = INVALID_HANDLE;
int                   g_handleTrendEMAfast          = INVALID_HANDLE;
int                   g_handleTrendEMAslow          = INVALID_HANDLE;

double                g_trailingLockUsd             = 0.0;
string                g_symbolBase                  = "";
string                g_symbolQuote                 = "";
bool                  g_calendarReady               = false;

//--- function declarations
bool     IsSymbolReady();
bool     IsNewBar();
int      UpdateUTBotSignal();
bool     CheckFilters(const int direction);
bool     CheckTrendFilter(const int direction);
bool     GetOscillatorValue(double &value);
double   NormalizeLots(double lots);
bool     OpenNewPosition(const int direction,const double lots);
uint     CountPositions(const int direction);
bool     HasOppositePositions(const int direction);
double   GetBasketProfit(const int direction);
double   GetTotalVolume(const int direction);
double   GetLastEntryPrice(const int direction);
void     ManageGroups();
void     ManageGroup(const int direction);
void     ManageDCA(const int direction,const double basketProfit);
void     CloseGroup(const int direction);
void     TrailGroup(const int direction,const double basketProfit);
double   PriceFromUSD(const double usd,const double volume);
void     HedgeIfNeeded(const int direction);
double   NormalizePrice(const double price);
bool     IsNewsFilterBlocking(const int direction);
void     InitializeSymbolCurrencies();

int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);

   InitializeSymbolCurrencies();

   if(InpUseNewsFilter)
     {
      g_calendarReady = CalendarIsSynchronized();
      if(!g_calendarReady)
        {
         datetime nowTime = TimeCurrent();
         if(!CalendarSelect(nowTime - 86400, nowTime + 86400))
            Print("Warning: Failed to pre-load calendar data. News filter will wait for synchronization.");
         else
            g_calendarReady = CalendarIsSynchronized();
        }
      if(!g_calendarReady)
         Print("Economic calendar not yet synchronized; news filter will be inactive until data arrives.");
     }

   if(SymbolInfoInteger(_Symbol,SYMBOL_TRADE_MODE)==SYMBOL_TRADE_MODE_DISABLED)
     {
      Print("Symbol trading disabled.");
      return(INIT_FAILED);
     }

   g_trailingLockUsd = MathMin(InpBasketTrailingLockUSD,InpBasketTakeProfitUSD);
   if(g_trailingLockUsd < InpBasketTrailingLockUSD)
      Print("Trailing lock USD trimmed to basket take profit USD.");

   if(InpStepPoints <= 0.0)
     {
      Print("Step points must be > 0.");
      return(INIT_FAILED);
     }

   //--- indicator handles
   g_handleATR = iATR(_Symbol,InpSignalTF,InpUTAtrPeriod);
   if(g_handleATR == INVALID_HANDLE)
     {
      Print("Failed to create ATR handle. Error: ",GetLastError());
      return(INIT_FAILED);
     }

   g_handleEMAfast = iMA(_Symbol,InpSignalTF,InpFastEMA,0,MODE_EMA,PRICE_CLOSE);
   g_handleEMAslow = iMA(_Symbol,InpSignalTF,InpSlowEMA,0,MODE_EMA,PRICE_CLOSE);
   if(g_handleEMAfast == INVALID_HANDLE || g_handleEMAslow == INVALID_HANDLE)
     {
      Print("Failed to create EMA handles. Error: ",GetLastError());
      return(INIT_FAILED);
     }

   if(InpUseTrendFilter)
     {
      g_handleTrendEMAfast = iMA(_Symbol,InpTrendTF,InpTrendFastEMA,0,MODE_EMA,PRICE_CLOSE);
      g_handleTrendEMAslow = iMA(_Symbol,InpTrendTF,InpTrendSlowEMA,0,MODE_EMA,PRICE_CLOSE);
      if(g_handleTrendEMAfast == INVALID_HANDLE || g_handleTrendEMAslow == INVALID_HANDLE)
        {
         Print("Failed to create trend EMA handles. Trend confirmation will be skipped. Error: ",GetLastError());
         if(g_handleTrendEMAfast != INVALID_HANDLE)
            IndicatorRelease(g_handleTrendEMAfast);
         if(g_handleTrendEMAslow != INVALID_HANDLE)
            IndicatorRelease(g_handleTrendEMAslow);
         g_handleTrendEMAfast = INVALID_HANDLE;
         g_handleTrendEMAslow = INVALID_HANDLE;
        }
     }

   if(InpUseOscillatorFilter)
     {
      if(InpOscillatorMode == OSC_RSI)
        {
         g_handleRSI = iRSI(_Symbol,InpSignalTF,InpRSIPeriod,PRICE_CLOSE);
         if(g_handleRSI == INVALID_HANDLE)
           {
            Print("Failed to create RSI handle. Error: ",GetLastError());
            return(INIT_FAILED);
           }
        }
      else
        {
         g_handleCCI = iCCI(_Symbol,InpSignalTF,InpCCIPeriod,PRICE_TYPICAL);
         if(g_handleCCI == INVALID_HANDLE)
           {
            Print("Failed to create CCI handle. Error: ",GetLastError());
            return(INIT_FAILED);
           }
        }
     }

   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(g_handleATR != INVALID_HANDLE)
      IndicatorRelease(g_handleATR);
   if(g_handleEMAfast != INVALID_HANDLE)
      IndicatorRelease(g_handleEMAfast);
   if(g_handleEMAslow != INVALID_HANDLE)
      IndicatorRelease(g_handleEMAslow);
   if(g_handleRSI != INVALID_HANDLE)
      IndicatorRelease(g_handleRSI);
   if(g_handleCCI != INVALID_HANDLE)
      IndicatorRelease(g_handleCCI);
   if(g_handleTrendEMAfast != INVALID_HANDLE)
      IndicatorRelease(g_handleTrendEMAfast);
   if(g_handleTrendEMAslow != INVALID_HANDLE)
      IndicatorRelease(g_handleTrendEMAslow);
  }

void OnTick()
  {
   if(!IsSymbolReady())
      return;

   RefreshRates();

   bool newBar = IsNewBar();
   bool shouldEvaluateSignal = newBar || !InpUseOnlyNewBarSignals;

   if(shouldEvaluateSignal)
     {
      int signal = UpdateUTBotSignal();
      if(signal != 0 && CheckFilters(signal))
        {
         if(IsNewsFilterBlocking(signal))
            Print("News filter active. Skipping new signal entry.");
         else
            g_pendingDirection = signal;
        }
     }

   ManageGroups();

   if(g_pendingDirection != 0)
     {
      if(IsNewsFilterBlocking(g_pendingDirection))
         return;

      if(CountPositions(g_pendingDirection) == 0)
        {
         double lot = NormalizeLots(InpInitialLot);
         if(OpenNewPosition(g_pendingDirection,lot))
            g_pendingDirection = 0;
        }
      else
        {
         // Already have exposure in this direction, ignore the pending signal
         g_pendingDirection = 0;
        }
     }
  }

bool IsSymbolReady()
  {
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
     {
      Print("No market data for symbol.");
      return(false);
     }
   return(true);
  }

bool IsNewBar()
  {
   datetime currentBarTime = iTime(_Symbol,InpSignalTF,0);
   if(currentBarTime == 0)
      return(false);

   if(currentBarTime != g_lastSignalBarTime)
     {
      g_lastSignalBarTime = currentBarTime;
      return(true);
     }
   return(false);
  }

int UpdateUTBotSignal()
  {
   if(iBars(_Symbol,InpSignalTF) < InpUTAtrPeriod + 3)
      return(0);

   MqlRates rates[3];
   ArraySetAsSeries(rates,true);
   if(CopyRates(_Symbol,InpSignalTF,1,3,rates) < 3)
      return(0);

   double atrValues[3];
   ArraySetAsSeries(atrValues,true);
   if(CopyBuffer(g_handleATR,0,1,3,atrValues) < 3)
      return(0);

   double atr = atrValues[0];
   if(atr <= 0.0)
      return(0);

   double hl2 = (rates[0].high + rates[0].low) * 0.5;
   double basicUpper = hl2 + InpUTAtrMultiplier * atr;
   double basicLower = hl2 - InpUTAtrMultiplier * atr;

   if(!g_utInitialized)
     {
      g_utFinalUpper = basicUpper;
      g_utFinalLower = basicLower;
      g_utTrend = 0;
      g_utInitialized = true;
      return(0);
     }

   double prevClose = rates[1].close;
   double finalUpper = g_utFinalUpper;
   double finalLower = g_utFinalLower;

   if(basicUpper < g_utFinalUpper || prevClose > g_utFinalUpper)
      finalUpper = basicUpper;
   if(basicLower > g_utFinalLower || prevClose < g_utFinalLower)
      finalLower = basicLower;

   int trend = g_utTrend;
   double closePrev = rates[0].close;

   if(closePrev > finalUpper)
      trend = DIR_BUY;
   else if(closePrev < finalLower)
      trend = DIR_SELL;

   int signal = 0;
   if(g_utTrend != 0 && trend != g_utTrend)
      signal = trend;

   g_utFinalUpper = finalUpper;
   g_utFinalLower = finalLower;
   g_utTrend = trend;

   return(signal);
  }

bool CheckFilters(const int direction)
  {
   double emaFast[2], emaSlow[2];
   ArraySetAsSeries(emaFast,true);
   ArraySetAsSeries(emaSlow,true);

   if(CopyBuffer(g_handleEMAfast,0,1,2,emaFast) < 2)
      return(false);
   if(CopyBuffer(g_handleEMAslow,0,1,2,emaSlow) < 2)
      return(false);

   double fast = emaFast[0];
   double slow = emaSlow[0];

   if(direction == DIR_BUY && fast <= slow)
      return(false);
   if(direction == DIR_SELL && fast >= slow)
      return(false);

   if(!CheckTrendFilter(direction))
      return(false);

   if(InpUseOscillatorFilter)
     {
      double oscValue = 0.0;
      if(!GetOscillatorValue(oscValue))
         return(false);

      if(InpOscillatorMode == OSC_RSI)
        {
         if(direction == DIR_BUY && oscValue < InpOscillatorBuyLevel)
            return(false);
         if(direction == DIR_SELL && oscValue > InpOscillatorSellLevel)
            return(false);
        }
      else
        {
         if(direction == DIR_BUY && oscValue < InpOscillatorBuyLevel)
            return(false);
         if(direction == DIR_SELL && oscValue > InpOscillatorSellLevel)
            return(false);
        }
     }
   return(true);
  }

bool CheckTrendFilter(const int direction)
  {
   if(!InpUseTrendFilter)
      return(true);

   if(g_handleTrendEMAfast == INVALID_HANDLE || g_handleTrendEMAslow == INVALID_HANDLE)
      return(true);

   double emaFast[1];
   double emaSlow[1];

   if(CopyBuffer(g_handleTrendEMAfast,0,0,1,emaFast) < 1)
      return(true);
   if(CopyBuffer(g_handleTrendEMAslow,0,0,1,emaSlow) < 1)
      return(true);

   double fast = emaFast[0];
   double slow = emaSlow[0];

   if(direction == DIR_BUY)
      return(fast > slow);

   return(fast < slow);
  }

bool GetOscillatorValue(double &value)
  {
   if(!InpUseOscillatorFilter)
      return(false);

   if(InpOscillatorMode == OSC_RSI)
     {
      double buffer[1];
      if(CopyBuffer(g_handleRSI,0,1,1,buffer) < 1)
         return(false);
      value = buffer[0];
      return(true);
     }
   double buffer[1];
   if(CopyBuffer(g_handleCCI,0,1,1,buffer) < 1)
      return(false);
   value = buffer[0];
   return(true);
  }

double NormalizeLots(double lots)
  {
   double minLot = SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   int    volDigits = (int)SymbolInfoInteger(_Symbol,SYMBOL_VOLUME_DIGITS);

   if(lotStep <= 0.0)
      lotStep = minLot;

   lots = MathMax(minLot,MathMin(maxLot,lots));
   lots = MathRound(lots/lotStep) * lotStep;
   lots = NormalizeDouble(lots,volDigits);
   return(lots);
  }

bool OpenNewPosition(const int direction,const double lots)
  {
   if(lots <= 0.0)
      return(false);

   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);

   bool result = false;
   if(direction == DIR_BUY)
      result = trade.Buy(lots,_Symbol,0.0,0.0,0.0,InpStrategyTag);
   else
      result = trade.Sell(lots,_Symbol,0.0,0.0,0.0,InpStrategyTag);

   if(!result)
     {
      PrintFormat("Failed to open %s %.2f lots. Error: %d",
                  direction == DIR_BUY ? "BUY" : "SELL",
                  lots,
                  GetLastError());
      ResetLastError();
     }
   return(result);
  }

uint CountPositions(const int direction)
  {
   uint count = 0;
   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type == POSITION_TYPE_BUY)
         ++count;
      if(direction == DIR_SELL && type == POSITION_TYPE_SELL)
         ++count;
     }
   return(count);
  }

bool HasOppositePositions(const int direction)
  {
   return(CountPositions(-direction) > 0);
  }

double GetBasketProfit(const int direction)
  {
   double total = 0.0;
   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type != POSITION_TYPE_BUY)
         continue;
      if(direction == DIR_SELL && type != POSITION_TYPE_SELL)
         continue;
      total += PositionGetDouble(POSITION_PROFIT);
     }
   return(total);
  }

double GetTotalVolume(const int direction)
  {
   double volume = 0.0;
   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type != POSITION_TYPE_BUY)
         continue;
      if(direction == DIR_SELL && type != POSITION_TYPE_SELL)
         continue;
      volume += PositionGetDouble(POSITION_VOLUME);
     }
   return(volume);
  }

double GetLastEntryPrice(const int direction)
  {
   double price = 0.0;
   datetime latest = 0;
   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type != POSITION_TYPE_BUY)
         continue;
      if(direction == DIR_SELL && type != POSITION_TYPE_SELL)
         continue;
      datetime openTime = (datetime)PositionGetInteger(POSITION_TIME);
      if(openTime >= latest)
        {
         latest = openTime;
         price = PositionGetDouble(POSITION_PRICE_OPEN);
        }
     }
   return(price);
  }

void ManageGroups()
  {
   ManageGroup(DIR_BUY);
   ManageGroup(DIR_SELL);

   if(InpEnableHedging)
     {
      HedgeIfNeeded(DIR_BUY);
      HedgeIfNeeded(DIR_SELL);
     }
  }

void ManageGroup(const int direction)
  {
   uint count = CountPositions(direction);
   if(count == 0)
      return;

   double profit = GetBasketProfit(direction);

   if(HasOppositePositions(direction) && InpBasketQuickCloseUSD > 0.0 && profit >= InpBasketQuickCloseUSD)
     {
      CloseGroup(direction);
      return;
     }

   if(profit >= InpBasketTakeProfitUSD)
     {
      CloseGroup(direction);
      return;
     }

   if(profit >= InpBasketTrailingStartUSD && g_trailingLockUsd > 0.0)
      TrailGroup(direction,profit);

   ManageDCA(direction,profit);
  }

void ManageDCA(const int direction,const double basketProfit)
  {
   if(IsNewsFilterBlocking(direction) && !InpAllowDcaDuringNews)
      return;

   if(basketProfit >= 0.0)
      return;

   uint count = CountPositions(direction);
   if(count == 0)
      return;

   if(count >= InpMaxPositionsPerSide)
      return;

   double marginLevel = AccountInfoDouble(ACCOUNT_MARGIN_LEVEL);
   if(marginLevel > 0.0 && marginLevel < InpHedgeMarginLevel)
      return;

   double lastPrice = GetLastEntryPrice(direction);
   if(lastPrice <= 0.0)
      return;

   double currentPrice = (direction == DIR_BUY) ? SymbolInfoDouble(_Symbol,SYMBOL_BID) : SymbolInfoDouble(_Symbol,SYMBOL_ASK);
   if(currentPrice <= 0.0)
      return;

   double diffPoints = (direction == DIR_BUY) ? (lastPrice - currentPrice) / _Point
                                              : (currentPrice - lastPrice) / _Point;
   if(diffPoints < InpStepPoints)
      return;

   double nextLot = InpInitialLot * MathPow(InpLotMultiplier,(int)count);
   nextLot = NormalizeLots(nextLot);

   if(nextLot <= 0.0)
      return;

   OpenNewPosition(direction,nextLot);
  }

void CloseGroup(const int direction)
  {
   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type != POSITION_TYPE_BUY)
         continue;
      if(direction == DIR_SELL && type != POSITION_TYPE_SELL)
         continue;

      ulong ticket = (ulong)PositionGetInteger(POSITION_TICKET);
      if(!trade.PositionClose(ticket))
        {
         PrintFormat("Failed to close ticket %I64u. Error: %d",ticket,GetLastError());
         ResetLastError();
        }
     }
  }

void TrailGroup(const int direction,const double basketProfit)
  {
   uint count = CountPositions(direction);
   if(count == 0)
      return;

   double lockTarget = MathMin(g_trailingLockUsd, basketProfit);
   if(lockTarget <= 0.0)
      return;

   double perPositionLock = lockTarget / (double)count;

   double stopLevel = SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   double freezeLevel = SymbolInfoInteger(_Symbol,SYMBOL_TRADE_FREEZE_LEVEL) * _Point;
   double requiredDistance = MathMax(stopLevel,freezeLevel);

   for(int i=PositionsTotal()-1; i>=0; --i)
     {
      if(!PositionSelectByIndex(i))
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;

      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(direction == DIR_BUY && type != POSITION_TYPE_BUY)
         continue;
      if(direction == DIR_SELL && type != POSITION_TYPE_SELL)
         continue;

      double volume = PositionGetDouble(POSITION_VOLUME);
      double entryPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double deltaPrice = PriceFromUSD(perPositionLock,volume);
      if(deltaPrice <= 0.0)
         continue;

      double marketPrice = (direction == DIR_BUY) ? SymbolInfoDouble(_Symbol,SYMBOL_BID)
                                                 : SymbolInfoDouble(_Symbol,SYMBOL_ASK);
      double newSL = (direction == DIR_BUY) ? entryPrice + deltaPrice
                                            : entryPrice - deltaPrice;

      if(direction == DIR_BUY)
        {
         if(newSL <= entryPrice)
            continue;
         if(requiredDistance > 0.0 && newSL > marketPrice - requiredDistance)
            newSL = marketPrice - requiredDistance;
         if(newSL <= entryPrice)
            continue;
        }
      else
        {
         if(newSL >= entryPrice)
            continue;
         if(requiredDistance > 0.0 && newSL < marketPrice + requiredDistance)
            newSL = marketPrice + requiredDistance;
         if(newSL >= entryPrice)
            continue;
        }

      newSL = NormalizePrice(newSL);
      if(currentSL != 0.0 && MathAbs(newSL - currentSL) < (_Point * 0.5))
         continue;

      ulong ticket = (ulong)PositionGetInteger(POSITION_TICKET);
      if(!trade.PositionModify(ticket,newSL,PositionGetDouble(POSITION_TP)))
        {
         PrintFormat("Failed to trail SL ticket %I64u. Error: %d",ticket,GetLastError());
         ResetLastError();
        }
     }
  }

double PriceFromUSD(const double usd,const double volume)
  {
   if(usd <= 0.0 || volume <= 0.0)
      return(0.0);

   double tickSize = SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   double tickValue = SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   if(tickSize <= 0.0 || tickValue <= 0.0)
      return(0.0);

   double delta = (usd * tickSize) / (volume * tickValue);
   return(MathAbs(delta));
  }

void HedgeIfNeeded(const int direction)
  {
   uint count = CountPositions(direction);
   if(count == 0)
      return;

   if(count < InpMaxPositionsPerSide)
      return;

   double marginLevel = AccountInfoDouble(ACCOUNT_MARGIN_LEVEL);
   if(marginLevel == 0.0 || marginLevel > InpHedgeMarginLevel)
      return;

   datetime nowTime = TimeCurrent();
   datetime lastHedgeTime = (direction == DIR_BUY) ? g_lastHedgeTimeBuy : g_lastHedgeTimeSell;

   if(lastHedgeTime != 0 && (nowTime - lastHedgeTime) < (int)InpHedgeCooldownMinutes * 60)
      return;

   if(!InpAllowHedgeDuringNews && IsNewsFilterBlocking(-direction))
      return;

   double groupVolume = GetTotalVolume(direction);
   double oppositeVolume = GetTotalVolume(-direction);
   double hedgeVolume = groupVolume - oppositeVolume;
   if(hedgeVolume <= 0.0)
      return;

   hedgeVolume = NormalizeLots(hedgeVolume);
   if(hedgeVolume <= 0.0)
      return;

   if(OpenNewPosition(-direction,hedgeVolume))
     {
      if(direction == DIR_BUY)
         g_lastHedgeTimeBuy = nowTime;
      else
         g_lastHedgeTimeSell = nowTime;
     }
  }

double NormalizePrice(const double price)
  {
   int digits = (int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS);
   return(NormalizeDouble(price,digits));
  }

bool IsNewsFilterBlocking(const int direction)
  {
   if(!InpUseNewsFilter)
      return(false);

   if(direction == DIR_BUY && !InpNewsBlockBuys)
      return(false);
   if(direction == DIR_SELL && !InpNewsBlockSells)
      return(false);

   if(!g_calendarReady)
      g_calendarReady = CalendarIsSynchronized();
   if(!g_calendarReady)
      return(false);

   datetime nowTime = TimeCurrent();
   datetime fromTime = nowTime - (long)InpNewsMinutesBefore * 60;
   datetime toTime = nowTime + (long)InpNewsMinutesAfter * 60;

   MqlCalendarValue values[];
   int events = CalendarValueHistory(values,fromTime,toTime);
   if(events <= 0)
      return(false);

   string baseCurrency = g_symbolBase;
   string quoteCurrency = g_symbolQuote;

   for(int i=0; i<events; ++i)
     {
      MqlCalendarEvent calendarEvent;
      if(!CalendarEventById(calendarEvent,values[i].event_id))
         continue;

      if(calendarEvent.importance < InpNewsMinImpact)
         continue;

      string eventCurrency = StringToUpper(calendarEvent.currency);
      if(eventCurrency != baseCurrency && eventCurrency != quoteCurrency && eventCurrency != "ALL")
         continue;

      datetime eventTime = calendarEvent.time;
      if(eventTime == 0)
         eventTime = values[i].time;
      if(eventTime == 0)
         continue;

      long diff = (long)MathAbs((double)(nowTime - eventTime));

      if(eventTime <= nowTime)
        {
         if(diff <= (long)InpNewsMinutesAfter * 60)
            return(true);
        }
      else
        {
         if(diff <= (long)InpNewsMinutesBefore * 60)
            return(true);
        }
     }
   return(false);
  }

void InitializeSymbolCurrencies()
  {
   string currencyBase = "";
   string currencyProfit = "";

   if(SymbolInfoString(_Symbol,SYMBOL_CURRENCY_BASE,currencyBase))
      g_symbolBase = StringToUpper(currencyBase);
   else
      g_symbolBase = "";

   if(SymbolInfoString(_Symbol,SYMBOL_CURRENCY_PROFIT,currencyProfit))
      g_symbolQuote = StringToUpper(currencyProfit);
   else
      g_symbolQuote = "";
  }
