name: hop_dong
description: "A Flutter project with Firebase login and role-based access."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # format số/ngày
  flutter_typeahead: ^5.2.0 # gợi ý MST (nếu muốn đẹp hơn Autocomplete)
  file_picker: ^8.0.0
  archive: ^3.6.1 # giải nén/đóng gói .docx (zip)
  http: ^1.2.2
  mime: ^1.0.5
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.0
  firebase_storage: ^12.3.0
  flutter_slidable: ^3.1.0
  android_intent_plus: ^4.0.2
  share_plus: ^10.0.2
  syncfusion_flutter_xlsio: ^25.1.37
  excel: ^4.0.2
  path_provider: ^2.0.15
  open_filex: ^4.3.4
  diacritic: ^0.1.3
  cloud_functions: ^5.6.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


