name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (for Flutter)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get
        working-directory: ./hop_dong

      - name: Build Flutter Web (no PWA cache)
        run: flutter build web --release --pwa-strategy=none
        working-directory: ./hop_dong

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: thanhhuy123-4e01c
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
